[package]
name = "ello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.3"
dotenv = "0.15.0"
tokio = { version = "1.33.0", features = ["full"] }
